name: hello world

on:
  push:
  workflow_call:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
